{% set name = "d3" %}
{% set version = "5.9.5" %}
{% set sha256 = "46cd381c60379cdc5572ce59975ded1ba9fcb295a0981db8a62b6ebf63a1b1f1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/d3/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: |
    tgz=$(npm pack)
    npm install -g $tgz

requirements:
  build:
    - nodejs
    
test:
  commands:
    - npm list -g d3
  requires:
    - nodejs
   

about:
  home: https://github.com/d3/d3
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Bring data to life with SVG, Canvas and HTML.'
  description: |
    D3 (or D3.js) is a JavaScript library for visualizing data using 
    web standards. D3 helps you bring data to life using SVG, Canvas 
    and HTML. D3 combines powerful visualization and interaction 
    techniques with a data-driven approach to DOM manipulation, 
    giving you the full capabilities of modern browsers and the 
    freedom to design the right visual interface for your data.  
  doc_url: https://github.com/d3/d3/wiki
  dev_url: https://github.com/d3/d3

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
