travis:
  secure:
    BINSTAR_TOKEN: uxqXC3YTMfI5JM/g4fwntttgYhcwkkh7uJEyThc7frGyYJO7KGGTolh6krPu5wxI/FSH9CHjvg0yrCtg4wB7OZQnzks26AriDFaZM3U6KFYy4hkNOp2CWR+/aE1l4pWHAeM0epJWQOdeWo2sYdRvAsnAdj3ArPWsL/A+9gzg2/MAAhPvUQV60Odkwv1Mu9CmhnQLRHaTgdmFUbHX8IQxsNM6sQQsJXw+f7p6xg3vy0kztg+Mp7HU/rYPp2ClyCRhfBQErxWFUM3PssRLjhJXoC8rPkews4RHVjYt9dShjd4Mb7sCbxnowYVrEZfA0h4azdpBL18v0tJzd95ROCjSzWuXKVidvwJq4Usa6zn+nwlQseuehHcviEOB4CxD7jcNWFLUvxcBWOFXPmuvNVYBMP/BS9ID8mW6jddUlL5ErMJ1I1BnIc6IisIZWSTk+0iXPe3Hut6uWTXWJeOAn1Nx6MnGHzscOvJvK/xEBrGougHw31afiCGCNBPSV0qwSWyxi4jtao2CzQvM4PHmFuxeQigxkAhNqR/6wluNl0+AKRPidurbM8fQyvkRvfyqHF4fHVGCuEwmoSCA2NjWzlPV29P8v0Tn46nyVBKaeWDoxGNlDGOd7YTq5YEKWXn0wHqDSmRxaC2JJGciZlIQ/y3TR4pkIjunEdeSdwJcXzRKNuA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
