travis:
  secure:
    BINSTAR_TOKEN: N2NQUCWjwpgeVyeLngEbSxzlWPgtg0xpIUDVehXbYop059IWFvV+P2x8OEQMoPZktJ7qzEHqutN2YLeTzNUMrcZ2xQa2b0f4HmgqaaQcu7h0VmMKF4ut7Ih40xhAr0xfqGfK4mPyI8cOoteHXqGzlR81Ii5XvLNXGF3evWZFRHsIZOvlo96h/Am9GKQipeYpb/MZx0cMWOvGA+L7cuMqmeL/D3A48ZZj+56UilTc2mAuNr1NzUTcvc9M5B383E756ap8q6YnMaugvaq1FXAblf0smYJpZnEkZbkIylSaC/WIvVFWBnJWzTAqeoGdvnS+O/i7g+pbev2WM+6PuN3bx4DwIYDxovHfUZmc/UGu5SBUO1lY8qwTlEiKkVnnajP2Zo2x6BFV3PQUAjMLKXDH/+iIxwEO0vIXErddkO4+yAFjKuyhh7aHxer8Y4e7y394C4vpKgGjOk0e6OLxpC3F1t0R8NqaCOazxmve3y+/PRyBRg8AVLQmnQMPlIzbVn9wsVwh/egJcIgng9vjwfxH/9GjJ3lQDAQu6m/ZkxR8UaZ3re8z+B12qO3wW1MYs+nx6kHlEfGwQkJxRt0nvjh9ISBjC2Lhkog4UyhTEDib8EsZ3+Bt/U4rk7WlR6uzoCpDnkfH48R05vQr3Zm4feWz6upLnJ3CmsDnxykufMFdIV4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
