travis:
  secure:
    BINSTAR_TOKEN: k3gyF2MhTFT268uB5eDaqd5aT3k4s4XQN1cY1/icukN68cHsWYn7fHbnPMGmy3qInGaGBeMhvlvnQTpRHMwlzXdo8T4nugZVBEaG0gNdlKftzkZCYXjsZpycAhhWDWN/JZ3PL94Cz6jhp0JI6XUXaIieGLwPVmqQzDQ1eYYYCmL2+Mbh4qoIg3oa9poZ08rux082o/569WjSrIVu53qo+xJbcwRnRuewXGktXMCL4QgS5jg9VYCqOkGGqB5jcJqqcHpwvJZU3mbb5p0ZFuUD7amk1rVS7RYcVaI9VYMh3ArDXnRnutW9ZaOHWMuZLS2d5O/osBj/ufmHZdjlvu+Lg2bst7SURONODs95ex0X6JcgV0TEJWiHq6eIDBbPzaZIBmLwyyVbD9h525zyxidLl6iu1llwKVolNtsVbxxWn3FmA38RKZTi/JmDa0M4+8QU4e8QmB8JKpa2lBUMiNAWgsPsbdVIgZGYSigMD5haCzppYidhCWd7cSxvX53SSxBosJRUKEJVOz3h0qdTPzT2v6DdxRmbfDyjdDxRS0u66JfvvCf+DqZaPnSBn1672joMEupXj64iKiiKBijg9YS6lnWLBliOzqMdSfJNR0OFSEnRugnYE+PCsRK48aOyLxHPfTg1buoKnd+4EDwZMT5eiqN4o31Zi8y8Ra6HwCCGOwg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
